
INSERT INTO `cat_distritos` (`id`, `region_id`, `distrito`, `created_at`, `updated_at`) VALUES
	(1, 4, 'I', NULL, NULL),
	(2, 4, 'II', NULL, NULL),
	(3, 4, 'III', NULL, NULL),
	(4, 4, 'IV', NULL, NULL),
	(5, 4, 'V', NULL, NULL),
	(6, 5, 'VI', NULL, NULL),
	(7, 5, 'VII', NULL, NULL),
	(8, 5, 'VIII', NULL, NULL),
	(9, 7, 'IX', NULL, NULL),
	(10, 7, 'X', NULL, NULL),
	(11, 7, 'XI', NULL, NULL),
	(12, 7, 'XII', NULL, NULL),
	(13, 2, 'XIII', NULL, NULL),
	(14, 2, 'XIV', NULL, NULL),
	(15, 2, 'XV', NULL, NULL),
	(16, 2, 'XVI', NULL, NULL),
	(17, 6, 'XVII', NULL, NULL),
	(18, 3, 'XVIII', NULL, NULL),
	(19, 3, 'XIX', NULL, NULL),
	(20, 1, 'XX', NULL, NULL),
	(21, 1, 'XXI', NULL, NULL),
	(22, 8, 'Otro', NULL, NULL),
	(23, 9, 'FGE', NULL, NULL);

